### PR TITLE
Add RELOAD option to support reload module.

### PR DESCRIPTION
**Pull request by ldsink**

### CODE REVIEW

**Review by operatorequals — CHANGES_REQUESTED** [review]
That's nice, just remove the `__pycache__` file.

**Comment by ldsink** [comment]
My fault. I removed pyc file and add *.pyc to gitignore.

**Comment by ldsink** [comment]
@operatorequals Can you release a new version to PyPI ? thanks.

**Comment by operatorequals** [comment]
Absolutely!

Just need some time, until Sunday it's gonna be up as 5.16.

**Comment by operatorequals** [comment]
The Release `0.5.16` contains your code:
https://pypi.org/project/httpimport/0.5.16

**Pull request merged**
